const products = [
  {
    id: 1,
    name: "Pie Buah",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Pie Buah.jpg",
  },
  {
    id: 2,
    name: "Risoles Ayam/Daging",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Risol Mayo.jpg",
  },
  {
    id: 3,
    name: "Pastel",
    category: "kering",
    price: 5000,
    image: "assets/images/products/pastel.jpg",
  },
  {
    id: 4,
    name: "Lapis",
    category: "basah",
    price: 5000,
    image: "assets/images/products/lapis.jpg",
  },
  {
    id: 5,
    name: "Wajik",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Wajik.jpg",
  },
  {
    id: 6,
    name: "Soes Maker",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Soes Maker.jpg",
  },
  {
    id: 7,
    name: "Mentuk Ayu",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Mentuk Ayu.jpg",
  },
  {
    id: 8,
    name: "Spikoe (Besar)",
    category: "kering",
    price: 85000,
    image: "assets/images/products/Spikoe (Besar).jpg",
  },
  {
    id: 9,
    name: "Roll Srikaya",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Roll Srikaya.jpg",
  },
  {
    id: 10,
    name: "Petulo",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Petulo.jpg",
  },
  {
    id: 11,
    name: "Zebra Cokelat (Besar)",
    category: "basah",
    price: 150000,
    image: "assets/images/products/Zebra Cokelat (Besar).jpg",
  },
  {
    id: 12,
    name: "Kue Lumpur Kentang",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Kue Lumpur Kentang.jpg",
  },
  {
    id: 13,
    name: "Nagasari Pisang",
    category: "basah",
    price: 4000,
    image: "assets/images/products/Nagasari Pisang.jpg",
  },
  {
    id: 14,
    name: "Brownies Kukus Coklat",
    category: "kering",
    price: 15000,
    image: "assets/images/products/Brownies Kukus Coklat.jpg",
  },
  {
    id: 15,
    name: "Kue Kering Nastar",
    category: "kering",
    price: 65000,
    image: "assets/images/products/Kue Kering Nastar.jpg",
  },
  {
    id: 16,
    name: "Kue Kering Putri Salju",
    category: "kering",
    price: 60000,
    image: "assets/images/products/Kue Kering Putri Salju.jpg",
  },
  {
    id: 17,
    name: "Donat Kentang",
    category: "basah",
    price: 7000,
    image: "assets/images/products/Donat Kentang.jpg",
  },
  {
    id: 18,
    name: "Kue Bolu Pandan",
    category: "kering",
    price: 25000,
    image: "assets/images/products/Kue Bolu Pandan.jpg",
  },
  {
    id: 19,
    name: "Kue Tart Ulang Tahun",
    category: "kering",
    price: 120000,
    image: "assets/images/products/Kue Tart Ulang Tahun.jpg",
  },
  {
    id: 20,
    name: "Kue Sus Mini",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Kue Sus Mini.jpg",
  },
];
