const products = [
  {
    id: 1,
    name: "Pie Buah",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Pie Buah.jpg",
  },
  {
    id: 2,
    name: "Risoles Ayam/Daging",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Risol Mayo.jpg",
  },
  {
    id: 3,
    name: "Pastel",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Pastel.jpg",
  },
  {
    id: 4,
    name: "Lapis",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Lapis.jpg",
  },
  {
    id: 5,
    name: "Wajik",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Wajik.jpg",
  },
  {
    id: 6,
    name: "Soes Lada",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Soes Lada.jpg",
  },
  {
    id: 7,
    name: "Mentuk Ayu",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Mentuk Ayu.jpg",
  },
  {
    id: 8,
    name: "Spikoe (Besar)",
    category: "kering",
    price: 85000,
    image: "assets/images/products/Spikoe (Besar).jpg",
  },
  {
    id: 9,
    name: "Roll Srikaya",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Roll Srikaya.jpg",
  },
  {
    id: 10,
    name: "Petulo",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Petulo.jpg",
  },
  {
    id: 11,
    name: "Zebra Cokelat (Besar)",
    category: "basah",
    price: 80000,
    image: "assets/images/products/Zebra Cokelat (Besar).jpg",
  },
  {
    id: 12,
    name: "Mendut",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Mendut.jpg",
  },
  {
    id: 13,
    name: "Donat Cokelat",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Donat Cokelat.jpg",
  },
  {
    id: 14,
    name: "Soes Fla (Bulat)",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Soes Fla (Bulat).jpg",
  },
  {
    id: 15,
    name: "Soes Maker",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Soes Maker 2.jpg",
  },
  {
    id: 16,
    name: "Ketan Kratok",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Ketan Kratok.png",
  },
  {
    id: 17,
    name: "Donat Cokelat Keju",
    category: "basah",
    price: 6000,
    image: "assets/images/products/Donat Cokelat Keju.png",
  },
  {
    id: 18,
    name: "Tahu Fantasi",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Tahu Fantasi.png",
  },
  {
    id: 19,
    name: "Zebra Cokelat",
    category: "kering",
    price: 5000,
    image: "assets/images/products/Zebra Cokelat.png",
  },
  {
    id: 20,
    name: "Zebra Pandan",
    category: "basah",
    price: 125000,
    image: "assets/images/products/Zebra Pandan (Besar).jpg",
  },
  {
    id: 21,
    name: "Roti Gulung",
    category: "kering",
    price: 85000,
    image: "assets/images/products/Roti Gulung.png",
  },
  {
    id: 22,
    name: "Kue Tok",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Kue Tok.jpg",
  },
  {
    id: 23,
    name: "Cake Salju",
    category: "basah",
    price: 5000,
    image: "assets/images/products/Cake Salju.jpg",
  },
    {
    id: 24,
    name: "Nampan (Mix)",
    category: "basah",
    price: 100000,
    image: "assets/images/products/Nampan (100k).jpg",
  },
];
